name: Image Resizer CI/CD

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd app-src && npm ci
      - run: cd app-src && zip -r ../function.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Create Lambda Bucket for source code
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ImageResizer-Bucket
          template: cloudformation/create_lambda_bucket.yml
          no-fail-on-empty-changeset: 1

      - name: Upload Lambda source code to Bucket
        run: pip install awscli && aws s3 cp function.zip s3://rclaveau-imageresizer-lambda-source

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ImageResizer
          template: cloudformation/deploy_lambda.yml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: 1
